name: Test Python and Angular

on:
  push:
    branches:
      - master

jobs:
  python_and_angular:
    name: Test Python and Angular
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js LTS
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.12'
          enable-cache: true

      - name: Python venv setup
        run: uv venv --python 3.12 "$GITHUB_WORKSPACE"/venv

      - name: Python dependencies and package install
        run: |
          uv pip install .
          uv pip install pytest
        working-directory: backend

      - name: Python tests
        run: |
          cp .env.tpl .env
          . "$GITHUB_WORKSPACE"/venv/bin/activate
          pytest
        working-directory: backend

      - name: Angular dependencies install
        run: npm ci
        working-directory: pulse-query-ng-web

      - name: Angular tests
        run: npm test
        working-directory: pulse-query-ng-web
